name: Test Workflow

on:
  push:
    branches: ["main"]
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"
      - name: Install Dependencies
        run: make init
      - name: Execute Unit Tests
        run: make test
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: testCoverage
          path: testCoverage
